import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated from the folder structure; ordering comes from each _category_.json
// and the sidebar_position front matter in the individual docs.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
